"""initial schema

Revision ID: 873715556cfa
Revises: 
Create Date: 2026-02-25 00:00:38.935802+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '873715556cfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('properties',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='America/Bogota', nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_messages',
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('file_references', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(length=20), server_default='received', nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("message_type IN ('text', 'photo', 'voice', 'video', 'document')", name='ck_raw_messages_message_type'),
    sa.CheckConstraint("processing_status IN ('received', 'processing', 'processed', 'needs_clarification', 'pending_retry', 'failed')", name='ck_raw_messages_processing_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id', 'telegram_message_id', name='uq_raw_messages_chat_msg')
    )
    op.create_index('ix_raw_messages_pending_processing', 'raw_messages', ['processing_status'], unique=False, postgresql_where="processing_status IN ('received', 'processing', 'pending_retry')")
    op.create_table('telegram_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('operator', 'manager', 'admin')", name='ck_telegram_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_users_telegram_id'), 'telegram_users', ['telegram_id'], unique=True)
    op.create_table('events',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('sequence_num', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("event_type IN ('ITEM_BROKEN', 'ITEM_MISSING', 'ITEM_SENT_TO_LAUNDRY', 'ITEM_RETURNED_FROM_LAUNDRY', 'MAINTENANCE_ISSUE', 'LOW_STOCK_ALERT', 'INCIDENT_ACKNOWLEDGED', 'INCIDENT_IN_PROGRESS', 'INCIDENT_RESOLVED', 'LAUNDRY_RETURNED', 'LAUNDRY_PARTIALLY_RETURNED', 'LAUNDRY_LOST')", name='ck_events_event_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['telegram_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['raw_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('sequence_num')
    )
    op.create_index('ix_events_payload_gin', 'events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_events_property_created', 'events', ['property_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_property_id'), 'events', ['property_id'], unique=False)
    op.create_index('ix_events_property_type_created', 'events', ['property_id', 'event_type', 'created_at'], unique=False)
    op.create_index('ix_events_sequence_num', 'events', ['sequence_num'], unique=False)
    op.create_table('incidents',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name='ck_incidents_priority'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'in_progress', 'resolved')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['telegram_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['telegram_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_property_id'), 'incidents', ['property_id'], unique=False)
    op.create_index('ix_incidents_unresolved', 'incidents', ['property_id', 'status'], unique=False, postgresql_where="status != 'resolved'")
    op.create_table('inventory_items',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('LINEN', 'TOWEL', 'KITCHEN', 'BATHROOM', 'FURNITURE', 'ELECTRONIC', 'OTHER')", name='ck_inventory_items_category'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'item_name', name='uq_inventory_property_item')
    )
    op.create_index(op.f('ix_inventory_items_property_id'), 'inventory_items', ['property_id'], unique=False)
    op.create_table('laundry_flows',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='sent', nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('total_pieces', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('sent', 'in_progress', 'returned', 'partially_returned', 'lost')", name='ck_laundry_flows_status'),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= sent_at', name='ck_laundry_flows_return_after_sent'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laundry_flows_property_id'), 'laundry_flows', ['property_id'], unique=False)
    op.create_table('pending_clarifications',
    sa.Column('original_message_id', sa.UUID(), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partial_event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['original_message_id'], ['raw_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_clarifications_original_message_id'), 'pending_clarifications', ['original_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_clarifications_original_message_id'), table_name='pending_clarifications')
    op.drop_table('pending_clarifications')
    op.drop_index(op.f('ix_laundry_flows_property_id'), table_name='laundry_flows')
    op.drop_table('laundry_flows')
    op.drop_index(op.f('ix_inventory_items_property_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_incidents_unresolved', table_name='incidents', postgresql_where="status != 'resolved'")
    op.drop_index(op.f('ix_incidents_property_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_events_sequence_num', table_name='events')
    op.drop_index('ix_events_property_type_created', table_name='events')
    op.drop_index(op.f('ix_events_property_id'), table_name='events')
    op.drop_index('ix_events_property_created', table_name='events')
    op.drop_index('ix_events_payload_gin', table_name='events', postgresql_using='gin')
    op.drop_table('events')
    op.drop_index(op.f('ix_telegram_users_telegram_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    op.drop_index('ix_raw_messages_pending_processing', table_name='raw_messages', postgresql_where="processing_status IN ('received', 'processing', 'pending_retry')")
    op.drop_table('raw_messages')
    op.drop_table('properties')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
